language: cpp
compiler:
  - gcc
script: debuild -b -us -uc --lintian-opts "-ivI"
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update -qq
  - sudo apt-get install -qq --no-install-recommends devscripts dpkg-dev lintian equivs
  - mk-build-deps --root-cmd sudo --tool "apt-get -qq --no-install-recommends" --install --remove
  - dch -v 0~git$(date +%Y%m%d%H%M)00-1~travis0 -m "Automated test-build."
  - mkdir -p ../data
