language: cpp
compiler:
  - gcc
  - clang
script: debuild -b -us -uc --lintian-opts "-ivI"
before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository ppa:mapnik/boost -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq --no-install-recommends devscripts dpkg-dev lintian equivs
  - mk-build-deps --root-cmd sudo --tool "apt-get -qq --no-install-recommends" --install --remove
  - dch -b -v 0.1.0~git$(date +%Y%m%d%H%M)00-1~travis0 -m "Automated test-build."
  - sudo apt-get install -qq --no-install-recommends libgl1-mesa-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev libpng12-dev libglew-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-regex-dev google-mock libgtest-dev doxygen graphviz po4a librsvg2-bin
notifications:
  email: false
