language: objective-c
compiler:
  - gcc
script: mkdir build; cd build; CC=/opt/local/bin/gcc-mp-4.8 CXX=/opt/local/bin/g++-mp-4.8 cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DOPENAL_SOUND=1 -DTESTS=1 && make all doc test && DESTDIR=. make install
before_install:
  - wget 'https://distfiles.macports.org/MacPorts/MacPorts-2.2.1-10.8-MountainLion.pkg' -O mp.pkg
  - sudo installer -pkg mp.pkg -target /
  - export PATH="/opt/local/bin:$PATH"
  - sudo port -v selfupdate
  - sudo port install gcc48
  - sudo port install python27 || sudo /opt/local/bin/port -f activate python27
  - sudo port install cmake libsdl libsdl_image libsdl_ttf boost libsndfile glew libicns librsvg
notifications:
  email: false
