language: cpp
compiler:
  - gcc
  - clang
script: debuild -b -us -uc --lintian-opts "-ivI"
before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository ppa:mapnik/boost -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq --no-install-recommends devscripts dpkg-dev lintian equivs
  - mk-build-deps --root-cmd sudo --tool "apt-get -qq --no-install-recommends" --install --remove
  - dch -b -v 0.1.2~git$(date +%Y%m%d%H%M)00-1~travis0 -m "Automated test-build."
notifications:
  email: false
